apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-app
  template:
    metadata:
      labels:
        app: next-app
    spec:
      serviceAccountName: next-app-service-account
      containers:
      - name: next-app
        image: bendrummond389/next-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000